version: '3'
services:
  nginx_pip:
    container_name: 'nginx_pip'
    image: 'nginx:latest'
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
      - ./nginx/conf.d/default-2.conf:/etc/nginx/nginx.conf
      - ./nginx/server.crt:/etc/nginx/server.crt
      - ./nginx/server.key:/etc/nginx/server.key
    ports:
      - '8000:80'
      - '443:443'
    networks:
      - backend
  php_pip:
    container_name: 'php_pip'
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
    ports:
      - '9000:9000'
    networks:
      - backend
  php_mongodb:
    container_name: 'php_mongodb'
    image: 'mongo:latest'
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  mongo-data:
